### ISSUE TITLE
How about just a dot?

### ISSUE THREAD

**Issue by Horse888** [Marxon13/M13BadgeView#2]
Can it show as a dot? says with no text but a small dot.

**Comment by Marxon13** [comment]
You mean make the string "." ?

**Comment by Horse888** [comment]
As you see, the attached last two items are just a red dot.

![image](https://cloud.githubusercontent.com/assets/749939/2691198/70aa4594-c376-11e3-9bfd-45ef6491ad0a.png)

**Comment by Marxon13** [comment]
I have not made an "inactive setting" for the badge at this moment. To get the same effect, you could set the minimumSize property to be half of what it normally is, then set the text to a single space. (You might have to change the font size to get a perfect circle.)

**Comment by Horse888** [comment]
Thanks, let me try.

**Comment by Marxon13** [comment]
Does it work?
