### ISSUE TITLE
Text don't center in circle

### ISSUE THREAD

**Issue by sbhhbs** [Marxon13/M13BadgeView#8]
remove all ceilf to have a more accurate frame solves this problem

**Comment by Marxon13** [comment]
The problem is that if I remove all the ceilf()s is that the text would be blurry. I would rather the text be <1pt off, than be blurry. Which for small text, makes it impossible to read.

**Comment by sbhhbs** [comment]
That may be the case, so maybe add a property to config this behavior, say 'preferCenterThanClearity'? Because to me, the offset from center is so obvious when text is small.

**Comment by Marxon13** [comment]
A toggle for pixel perfect has been added.
